config/routes.rb
FiredevsWebsystem::Application.routes.draw do

  resources :incident_types

  resources :final_notes, except: [:new], controller: :notes, type: FinalNote.to_s
  resources :in_progress_notes, except: [:new], controller: :notes, type: InProgressNote.to_s
  
  [:notes, :final_notes, :in_progress_notes].each do |note_kind|
    resources note_kind, except: [:new, :destroy] do 
      new{ get ':dispatch_id', action: 'new', as: '', controller: :notes, type: note_kind }
      get 'new_final/:dispatch_id', action: 'new_final', as: 'new_final', controller: :notes, type: note_kind, on: :collection
    end
  end
  resources :places

  root "complaints#new"

  resources :guard_groups

  resources :vehicles

  get "versions", :to => 'versions#index', as: :paper_trail_versions
  get 'version/:id', :to => 'versions#show', as: :paper_trail_version

  resources :fireman_hierarchies

  resources :firemen do
    get 'by_division/:division_id', action: :by_division, on: :collection
  end

  resources :fireman_classifications

  resources :divisions do
    get 'by_fire_department/:fire_department_id', action: :by_fire_department, on: :collection
  end

  resources :complaints, path_names: { destroy: 'mark_as_user_error' }  do 
    get 'report', action: :report, as: 'report', on: :member
    get 'mark_as_fake', action: :mark_as_fake, as: 'mark_as_fake', on: :member
    get 'search', action: :search, on: :collection # params: see action on controller
    get 'show_map', action: :show_map, on: :collection
  end

  resources :fire_departments

  resources :address_types

  resources :transferences, except: [:edit, :update], path_names: { destroy: 'undone' } do
    get 'search', action: :search, on: :collection # params: see action on controller
    get "set_place", action: :set_place, on: :collection# params: place_id
    get "add_vehicles", action: :add_vehicle, on: :collection# params: ids_on_list, vehicle_id
    get "add_firemen", action: :add_fireman, on: :collection# params: ids_on_list, fireman_id
    get "remove_vehicle", action: :remove_vehicle, on: :collection# params: ids_on_list, vehicle_id
    get "remove_fireman", action: :remove_fireman, on: :collection# params: ids_on_list, fireman_id
  end

  resources :people

  devise_for :users, path: 'auth', skip: [:registrations], path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }, controllers: {
    sessions: 'sessions'
  }

  get "guards/history", :to => 'guards#search', as: :guards_search
  get "guards/active"
  get "guards/add_guard_group"
  get "guards/add_editing"
  post "guards/update"
  delete "guards/destroy/:fireman_id", to: 'guards#destroy', as: :guards_destroy

  resources :dispatches, except: [:edit, :update, :index, :show, :destroy, :new] do
    get 'add_vehicle/:vehicle_id', action: 'add_vehicle', on: :collection, format: :json, as: 'add_vehicle'
    get 'add_fireman/:vehicle_id/:fireman_id', action: 'add_fireman', on: :collection, format: :json, as: 'add_fireman'
    new { get ':complaint_id', action: 'new', as: '' }
    get 'report', action: :report, as: 'report', on: :member
  end

    resources :users
    resources :users, path: "admins", as: "admins"

end

app/models/transference.rb
class Transference < ActiveRecord::Base
  belongs_to :place
  has_many :transference_histories, dependent: :destroy

  def transferables 
    firemen + vehicles
  end

  has_many :fireman_transference_histories, -> { where transferable_type: 'Fireman' },
    class_name: TransferenceHistory

  def self.search_by_day time
    return all if time.nil?
    beginning_of_day = DateTime.new(time.year, time.month, time.day, 0, 0, 0, 0)
    end_of_day = DateTime.new(time.year, time.month, time.day, 24, 0, 0, 0)
    where('transferences.created_at >= :beginning_of_day AND transferences.created_at <= :end_of_day', {beginning_of_day: beginning_of_day, end_of_day: end_of_day})
  end

  def self.by_origin place_id
    return all if place_id.nil?
    includes(:transference_histories).where(transference_histories: { original_address_id: Place.find(place_id).address.id })
  end

  def self.by_destination place_id
    return all if place_id.nil?
    where(transferences: { place_id: place_id })
  end

  def self.by_fireman fireman_id
    return all if fireman_id.nil?
    includes(:transference_histories).where(transference_histories: { transferable_id: fireman_id, transferable_type: Fireman.to_s })
  end

  def self.by_vehicle vehicle_id
    return all if vehicle_id.nil?
    includes(:transference_histories).where(transference_histories: { transferable_id: vehicle_id, transferable_type: Vehicle.to_s })
  end


  has_many :firemen, through: :transference_histories, source: :transferable, source_type: 'Fireman'
  has_many :vehicles, through: :transference_histories, source: :transferable, source_type: 'Vehicle'

  has_many :vehicle_transference_histories, -> { where transferable_type: 'Vehicle' },
    class_name: TransferenceHistory
    

  validates :reason, presence: true, length: { in: 10..1000 }
  validates :place, presence: true

  delegate :name, to: :place, prefix: true
  
  accepts_nested_attributes_for :transference_histories, allow_destroy: true

  before_create :transfer!

  def transfer!
    now = Time.now
    Transference.transaction do 
      transference_histories.each do |history|
        transferable = history.transferable
        history.original_address = transferable.current_address#self.transference_histories.last.try(:transference).try(:place) || transferable.division.place
        history.originally_available = transferable.available
        history.original_division = transferable.division

        transferable.available = self.available
        transferable.current_address = self.place.address
        if self.place.has_division?
          transferable.division = self.place.division
        end      
        transferable.save!

        # close active guards
        transferable.guards.active.last.close_at!(now) if transferable.is_a?(Fireman) && transferable.active_guard?

        history.save!
      end
    end
  end

  def undone!
    raise Transference::CanNotBeUndone unless can_be_undone?
    Transference.transaction do 
      transferables.each do |transferable|
        last_thistory = transferable.transference_histories.last
        #transferable.division = last_thistory.original_place.division if last_thistory.original_place.has_division?
        transferable.current_address = last_thistory.original_address
        transferable.division = last_thistory.original_division
        transferable.available = last_thistory.originally_available?
        transferable.save!
      end
      self.destroy
    end
  end

  def can_be_done?
    future_transferables.each do |transferable|
      return false if transferable.dispatched
    end
    true
  end

  def can_be_undone?
    # TODO: a super query for better performance
    if place.has_division?
      firemen_ids = firemen.map(&:id)
      return false unless DispatchesVehicles.where(fireman_id: firemen_ids).where("created_at >= ?", self.created_at).empty?
      return false unless VehiclesFiremen.where(fireman_id: firemen_ids).where("created_at >= ?", self.created_at).empty?
      vehicles_ids = vehicles.map(&:id)
      return false unless DispatchesVehicles.where(vehicle_id: vehicles_ids).where("created_at >= ?", self.created_at).empty?
      # false
    end
    true
  end

  validate :at_least_one_transferable, :can_be_done

  attr_accessor :future_transferables
  private

  def at_least_one_transferable
    if future_transferables.nil? || future_transferables.size < 1
      self.errors.add :base, :at_least_one_transferable
    end
  end

  def can_be_done
    unless can_be_done?
      self.errors.add :base, :can_not_be_done
    end
  end

  # Cast the ID column to a string in Mysql
  # when searching with Ransack.
  # Allows searches with _cont and _eq predicates.
  # From https://github.com/ernie/ransack/issues/224
  ransacker :id do
    Arel::Nodes::SqlLiteral.new("substring(CAST(transferences.id as CHAR(12)),length(transferences.id))")
  end
end
class Transference::CanNotBeUndone < StandardError ; end

app/controllers/transferences_controller.rb
class Transference::SearchInvalidDate < StandardError ; end
class TransferencesController < ApplicationController
  before_action :set_transference, only: [:show, :edit, :update, :destroy]

  before_action :set_variables, only: [:create, :edit, :new, :update]

  before_action :set_as_reportable, only: [:index, :search]

  rescue_from Transference::CanNotBeUndone do |e|
    redirect_to transferences_path, alert: t('errors.messages.transference.can_not_be_undone')
  end

  # GET /transferences
  # GET /transferences.json
  def index
    @query = Transference.search(query_param)
    @transferences = @query.result
    check_as_report
  end

  def set_place
    @place = Place.find_by(id: params[:place_id])
  end

  def add_fireman
    @firemen_on_list = Fireman.where(id: _add_to_params_array(params[:ids_on_list],params[:fireman_id]) )
    @firemen_for_select = _firemen - @firemen_on_list
    respond_to { |f| f.js{ render 'update_firemen' } }
  end

  def add_vehicle
    @vehicles_on_list = Vehicle.where(id: _add_to_params_array(params[:ids_on_list],params[:vehicle_id]))
    @vehicles_for_select = _vehicles - @vehicles_on_list
    respond_to { |f| f.js{ render 'update_vehicles' } }
  end


  def remove_fireman
    @firemen_on_list = Fireman.where(id: _remove_from_params_array(params[:ids_on_list],params[:fireman_id]))
    @firemen_for_select = _firemen - @firemen_on_list
    respond_to { |f| f.js{ render 'update_firemen' } }
  end

  def remove_vehicle
    @vehicles_on_list = Vehicle.where(id: _remove_from_params_array(params[:ids_on_list],params[:vehicle_id]))
    @vehicles_for_select = _vehicles - @vehicles_on_list
    respond_to { |f| f.js{ render 'update_vehicles' } }
  end

  # GET /transferences/1
  # GET /transferences/1.json
  def show
  end

  # GET /transferences/new
  def new
    @transference = Transference.new
  end

  # POST /transferences
  # POST /transferences.json
  def create
    @transference = Transference.new(transference_params)
    @firemen_on_list = Fireman.where(id: _ids_from_params('Fireman'))
    @vehicles_on_list = Vehicle.where(id: _ids_from_params('Vehicle'))
    @transference.future_transferables = @firemen_on_list + @vehicles_on_list
    respond_to do |format|
      if @transference.save
        format.html { redirect_to @transference, notice: 'Transference was successfully created.' }
        format.json { render action: 'show', status: :created, location: @transference }
      else
        format.html { render action: 'new' }
        format.json { render json: @transference.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /transferences/1
  # DELETE /transferences/1.json
  def destroy
    @transference.undone!
    respond_to do |format|
      format.html { redirect_to transferences_url }
      format.json { head :no_content }
    end
  end


  rescue_from Transference::SearchInvalidDate do |e|
    # Only happens on 'search' action
    @transferences = safe_search
    _error_render_method(t('errors.messages.invalid_date').capitalize, "search", "search", :set_variables)
  end

  def search
    @firemen = Fireman.all
    @vehicles = Vehicle.all
    @places = Place.all
    @transferences = safe_search.search_by_day(criteria_dates_params[:created_at])
    check_as_report
  end

  def report
    authorize! :print, Transference
    render layout: 'report'
  end

  private
    def check_as_report
      if params[:as_report]
        authorize! :print, Transference
        respond_to do |format|
          format.json{ render json: @transferences }
          format.html{ render action: 'report', layout: 'report' }
        end
      else
        @transferences = @transferences.page(page_param)
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_transference
      @transference = Transference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transference_params
      params.require(:transference).permit(:reason, :place_id, :available,
        transference_histories_attributes: [ :id, :transferable_id, :transferable_type, :_destroy])
    end

    def _firemen
      Fireman.not_dispatched
    end

    def _vehicles
      Vehicle.not_dispatched
    end

    def set_variables
      @places = Place.all
      @vehicles_for_select = _vehicles
      @firemen_for_select = _firemen
    end
    def query_param
      params.require(:q) if params[:q]
    end

    def _add_to_params_array(json_array, item)
      JSON.parse(json_array)+[item]
    end

    def _remove_from_params_array(json_array, item)
      JSON.parse(json_array)-[item]
    end

    def _ids_from_params type
      ( (transference_params[:transference_histories_attributes]||[]).map do |thp|
        thp[:transferable_id] if thp[:transferable_type] == type
      end.compact)
    end

    def safe_search
      Transference.by_fireman(criteria_model_params('fireman')[:fireman_id])
        .by_origin(criteria_places_params[:origin_id])
        .by_destination(criteria_places_params[:destination_id])
        .by_vehicle(criteria_model_params('vehicle')[:vehicle_id])
        .order(created_at: :desc)
    end

    def criteria_model_params model
      r = params.require(:criteria).permit(:"#{model}_id").delete_if{ |k,v| v.blank? } if params[:criteria]
      r || {}
    end

    def criteria_dates_params 
      if params[:criteria]
        a = params.require(:criteria).permit(:created_at)
        a.delete_if{ |k, v| v.blank? }.each do |k,v|
          begin
            a[k] = Time.strptime(v,"%d-%m-%Y")
          rescue 
            raise Transference::SearchInvalidDate
          end
        end
      else {} end
    end

    def criteria_places_params
      return params.require(:criteria).permit(:destination_id, :origin_id).delete_if{|k,v| v.blank? } if params[:criteria]
      return {}
    end

end

app/helpers/transferences_helper.rb
module TransferencesHelper
  def options_for_fireman_search_select params, name=nil
    if (params[:criteria] || {})[:fireman_id].blank?
      content_tag(:option, 
        t('general.actions.search', entity: t('general.models.fireman')).capitalize, 
        :value=>"")+options_from_collection_for_select(@firemen, 'id', 'compound_name')
    else
      options_from_collection_for_select(@firemen, 'id', 'compound_name', params[:criteria][:fireman_id])
    end
  end

  def options_for_vehicle_search_select params, name=nil
    if (params[:criteria] || {})[:vehicle_id].blank?
      content_tag(:option, 
        t('general.actions.search', entity: t('general.models.vehicle')).capitalize, 
        :value=>"")+options_from_collection_for_select(@vehicles, 'id', 'compound_name')
    else
      options_from_collection_for_select(@vehicles, 'id', 'compound_name', params[:criteria][:vehicle_id])
    end
  end
  
  def options_for_place_search_select params, name
    if (params[:criteria] || {})[:"#{name}"].blank?
      content_tag(:option, 
        t('general.actions.search', entity: t('general.models.place')).capitalize, 
        :value=>"")+options_from_collection_for_select(@places, 'id', 'name')
    else
      options_from_collection_for_select(@places, 'id', 'name', params[:criteria][:"#{name}"])
    end
  end


  def criteria_select(model, options={})
    css_class ||= "col-lg-6"
    options[:name] = "#{options[:name] || model}_id"
    name =  "criteria[#{options[:name]}]"
    translated_text = options[:translated_text] || "general.models.#{model}"
    options_method = "options_for_#{model}_search_select"
    html = <<-html
      <div class='#{css_class}'>
        <div class='form-group'>
          #{ label_tag name, t('general.actions.search', entity: t(translated_text)).capitalize }
          #{ select_tag name, self.send(options_method, params, options[:name]), { class: 'form-control combobox' } }
        </div>
      </div>
    html
    html.html_safe
  end
end

app/views/transferences/_fireman_transference_histories.html.erb
<div class="form-group">
  <%= label_tag :fireman_select, t('general.models.fireman').capitalize   %>
  <%= select_tag :fireman_select, options_from_collection_for_select(@firemen_for_select, :id, :compound_name), {prompt: t('general.actions.search', entity: t('general.models.fireman')).capitalize, class: 'form-control combobox', id: 'fireman_select', :"data-list" => '#fireman_list', :"data-link" => add_firemen_transferences_path} %>
</div>
<% firemen = @firemen_on_list || [] %>
<% unless firemen.empty? %>
  <div  class="table-responsive">
    <div class="dataTables_wrapper form-inline" role="grid">
      <table class="table table-hover dataTable no-footer">
        <thead>
          <tr>
            <th><%= t('general.attributes.code').capitalize %></th>
            <th><%= t('general.attributes.full_name').capitalize %></th>
            <th><%= t('general.models.division').capitalize %></th>
            <th></th>
          </tr>
        </thead>
        <tbody id="fireman_list">
          <% firemen.each do |fireman| %>
            <tr>
              <td>
                <%= truncate fireman.code, length: 10 %>
                <%= hidden_field_tag('transference[transference_histories_attributes][][transferable_id]', fireman.id, id: "fireman_transference_histories_fireman_id_#{fireman.id}") %>
                <%= hidden_field_tag('transference[transference_histories_attributes][][transferable_type]', 'Fireman', id: "fireman_transference_histories_fireman_type_#{fireman.id}") %>
              </td>
              <td><%= truncate fireman.full_name, length: 30 %></td>
              <td><%= truncate fireman.division_name, length: 30 %></td>
              <td class="action">
                <a href="#fireman_list" data-no-turbolink="true" data-id="<%= fireman.id %>" data-link="<%= remove_fireman_transferences_path %>" data-transference-remove="fireman" data-list="#fireman_list">
                  <span class="glyphicon glyphicon-trash"></span>
                </a>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/transferences/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= form_for(@transference, html: { role: 'form' }, validate: true) do |f| %>
      <% if @transference.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@transference.errors.count, "error") %>
            prohibited this transference from being saved:</h2>
          <ul>
            <% @transference.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :reason, t('general.attributes.reason').capitalize   %><br>
        <%= f.text_area :reason, class: 'form-control'  %>
      </div>
      <div class="form-group">
        <%= f.label :available, t('general.attributes.available').capitalize.pluralize(I18n.locale) %>
        <%= f.check_box :available %>
      </div>
      <div class="form-group">
        <%= f.label :place_id, t('general.attributes.destination').capitalize   %><br>
        <%= f.collection_select(:place_id, @places, :id, :name, {prompt: t('general.actions.search', entity: t('general.models.place')).capitalize}, class: 'form-control combobox', id: 'place_select', :"data-link" => set_place_transferences_path, :"data-id" => 'place' ) %>
      </div>
      <div id='place'>
        <%= render partial: 'place', locals: { place: @transference.place } %>
      </div>
      <div id="fireman_transference_histories">
        <%= render partial: 'fireman_transference_histories' %>
      </div>
      <div id="vehicle_transference_histories">
        <%= render partial: 'vehicle_transference_histories' %>
      </div>
      <div class="row">
        <div class="col-lg-12 text-right actions">
          <%= actions[f] %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/transferences/_index.html.erb
<% if @transferences.empty? %>
  <div class="alert alert-info alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
    <%= t('general.registers_not_found') %>
  </div>
<% else %>
  <%= results_quantity @transferences.count %>
  <div  class="table-responsive">
    <div class="dataTables_wrapper form-inline" role="grid">
      <table class="table table-hover dataTable no-footer">
        <thead>
          <tr>
            <th>
              <%= t('general.attributes.number').capitalize %>
            </th>
            <th>
              <%= t('general.attributes.reason').capitalize %>
            </th>
            <th>
              <%= t('general.attributes.destination').capitalize %>
            </th>
            <th>
              <%= t('general.attributes.available').capitalize %>
            </th>
            <th>
              <%= t('general.attributes.created_at').capitalize %>
            </th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @transferences.each do |transference| %>
            <tr>
              <td>
                <%= truncate transference.id.to_s, length: 10 %>
              </td>
              <td>
                <%=  truncate transference.reason, length: 50  %>
              </td>
              <td>
                <%= truncate transference.place.name, length: 40 %>
              </td>
              <td><%= t("general.#{(!!transference.available).to_s}_significant") %></td>
              <td>
                <%= truncate l(transference.created_at, format: :long), length: 40 %>
              </td>
              <td class="action">
                <%= link_to transference do %>
                  <span class="glyphicon glyphicon-info-sign"></span>
                  <%= t('general.links.show').capitalize %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/transferences/_place.html.erb
<% unless place.nil? %>
  <div class="panel-body">
    <div class="row">
      <div class="col-lg-3"><b><%= t('general.attributes.address').capitalize %>:</b></div>
      <div class="col-lg-9"><%= place.address.name %>
      </div>
      <% unless place.address.references.nil? or place.address.references.empty? %>
        <div class="col-lg-3"><b><%= t('general.attributes.references').capitalize %>:</b></div>
        <div class="col-lg-9">
          <%= place.address.references %>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <%= gmap_show(place.address.latitude, place.address.longitude) %>
      </div>
    </div>
  </div>
<% end %>

app/views/transferences/_vehicle_transference_histories.html.erb
<div class="form-group">
  <%= label_tag :vehicle_select, t('general.models.vehicle').capitalize   %>
  <%= select_tag :vehicle_select, options_from_collection_for_select(@vehicles_for_select, :id, :compound_name), {prompt: t('general.actions.search', entity: t('general.models.vehicle')).capitalize, class: 'form-control combobox', id: 'vehicle_select', :"data-list" => '#vehicle_list', :"data-link" => add_vehicles_transferences_path} %>
</div>
<% vehicles = @vehicles_on_list || [] %>
<% unless vehicles.empty? %>
  <div  class="table-responsive">
    <div class="dataTables_wrapper form-inline" role="grid">
      <table class="table table-hover dataTable no-footer">
        <thead>
          <tr>
            <th><%= t('general.attributes.code').capitalize %></th>
            <th><%= t('general.models.division').capitalize %></th>
            <th></th>
          </tr>
        </thead>
        <tbody id="vehicle_list">
          <% vehicles.each do |vehicle| %>
            <tr>
              <td>
                <%= truncate vehicle.code, length: 10 %>
                <%= hidden_field_tag('transference[transference_histories_attributes][][transferable_id]', vehicle.id, id: "vehicle_transference_histories_vehicle_id_#{vehicle.id}") %>
                <%= hidden_field_tag('transference[transference_histories_attributes][][transferable_type]', 'Vehicle', id: "vehicle_transference_histories_vehicle_type_#{vehicle.id}") %>
              </td>
              <td>
                <%= truncate vehicle.division_name, length: 30 %>
              </td>
              <td class="action">
                <a href="#vehicle_list" data-no-turbolink="true" data-id="<%= vehicle.id %>" data-link="<%= remove_vehicle_transferences_path %>" data-transference-remove="vehicle" data-list="#vehicle_list">
                  <span class="glyphicon glyphicon-trash"></span>
                </a>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/transferences/edit.html.erb
<div class="col-lg-9">
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= t('general.editing', entity: t("general.models.transference")).capitalize %>
    </div>
    <div class="panel-body">
      <%= render partial: 'form', locals: { actions: actions(t('general.models.transference')) } %>
    </div>
  </div>
</div>

app/views/transferences/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-lg-5">
        <%= t('general.listing', entity: t('general.models.transference').pluralize(I18n.locale)).capitalize %>
      </div>
      <div class="col-lg-7">
        <%= panel_heading_search_form_for(@query, :place_name, :reason, :id) %>
      </div>
    </div>
  </div>
  <div class="panel-body">
   <%= render partial: 'index' %>
  </div>
  <div class="panel-footer">
    <div class="row">
      <div class="col-lg-9">
        <%= will_paginate @transferences %>
      </div>
      <% if can? :create, Transference %>
        <div class="col-lg-3 text-right">
          <%= link_to new_transference_path, class: 'btn btn-primary' do %>
            <span class="glyphicon glyphicon-plus"></span>
            <%= t('general.actions.create', entity: t('general.models.transference')).capitalize %>
          <% end %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/transferences/new.html.erb
<div class="col-lg-9">
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= t('general.actions.create', entity: t('general.models.transference')).capitalize %>
    </div>
    <div class="panel-body">
      <%= render partial: 'form', locals: { actions: actions(t('general.models.transference')) } %>
    </div>
  </div>
</div>

app/views/transferences/report.html.erb
<%= render layout: 'reports/table', locals: { list: @transferences, 
      header_attributes: [
              t('general.attributes.number').capitalize,
              t('general.attributes.reason').capitalize,
              t('general.attributes.destination').capitalize,
              t('general.attributes.created_at').capitalize ],
      listing_text: "#{t('general.report_of', entity: t('general.models.transference').pluralize(I18n.locale)).capitalize} - #{l(Time.now, format: :long)}"   }  do |transference| %>
    <tr>
      <td>
        <%= truncate transference.id.to_s, length: 10 %>
      </td>
      <td>
        <%=  truncate transference.reason, length: 50  %>
      </td>
      <td>
        <%= truncate transference.place.name, length: 40 %>
      </td>
      <td>
        <%= truncate l(transference.created_at, format: :long), length: 40 %>
      </td>
    </tr>
<% end %>

app/views/transferences/search.html.erb
  <div class="col-lg-11">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= "#{t('general.models.transference').pluralize(I18n.locale).capitalize}" %>
      </div>
      <div class="panel-body" >
        <br/>
        <div class="row">
          <%= form_tag(search_transferences_path, { method: :get, role: 'form', class: "" }) do |transference_groups_form| %>
            
            <%= criteria_select 'fireman' %>
            <%= criteria_select 'vehicle' %>

            <div class="col-lg-6">
              <div class="form-group">
                <%= label_tag 'criteria[created_at]', t('general.attributes.created_at').capitalize %>
                <%= text_field_tag('criteria[created_at]', (params[:criteria] || {})[:created_at], { :"data-date-format" => 'dd-mm-yyyy', class: 'form-control', id: 'criteria_created_at' }) %>
              </div>
            </div>

            <%= criteria_select 'place', {translated_text: 'attributes.transferences.origin', name: 'origin'} %>
            <%= criteria_select 'place', {translated_text: 'attributes.transferences.destination', name: 'destination'} %>
            
            <div class="col-lg-12">
              <div class="form-group">
                <%= submit_tag t('general.actions.search', entity: t('general.models.transference')).capitalize, class: 'btn btn-primary' %>
                <%= link_to t('general.links.show_all').capitalize, search_transferences_path, class: 'btn btn-default', style: 'right: 35px; position: absolute' %>
              </div>
            </div>
          <% end %>
        </div>
        <br/>
        <%= render partial: 'index' %>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-lg-12">
            <%= will_paginate @transferences %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/transferences/set_place.js.erb
$('#place').html("<%= escape_javascript(raw render(partial: 'place', locals: {place: @place}))%>");

app/views/transferences/update_firemen.js.erb
$('#fireman_transference_histories').html("<%= escape_javascript(raw render(partial: 'fireman_transference_histories'))%>");
$("select.combobox").combobox();

app/views/transferences/update_vehicles.js.erb
$('#vehicle_transference_histories').html("<%= escape_javascript(raw render(partial: 'vehicle_transference_histories'))%>");
$("select.combobox").combobox();