config/routes.rb
FiredevsWebsystem::Application.routes.draw do

  resources :incident_types

  resources :final_notes, except: [:new], controller: :notes, type: FinalNote.to_s
  resources :in_progress_notes, except: [:new], controller: :notes, type: InProgressNote.to_s
  
  [:notes, :final_notes, :in_progress_notes].each do |note_kind|
    resources note_kind, except: [:new, :destroy] do 
      new{ get ':dispatch_id', action: 'new', as: '', controller: :notes, type: note_kind }
      get 'new_final/:dispatch_id', action: 'new_final', as: 'new_final', controller: :notes, type: note_kind, on: :collection
    end
  end
  resources :places

  root "complaints#new"

  resources :guard_groups

  resources :vehicles

  get "versions", :to => 'versions#index', as: :paper_trail_versions
  get 'version/:id', :to => 'versions#show', as: :paper_trail_version

  resources :fireman_hierarchies

  resources :firemen do
    get 'by_division/:division_id', action: :by_division, on: :collection
  end

  resources :fireman_classifications

  resources :divisions do
    get 'by_fire_department/:fire_department_id', action: :by_fire_department, on: :collection
  end

  resources :complaints, path_names: { destroy: 'mark_as_user_error' }  do 
    get 'report', action: :report, as: 'report', on: :member
    get 'mark_as_fake', action: :mark_as_fake, as: 'mark_as_fake', on: :member
    get 'search', action: :search, on: :collection # params: see action on controller
    get 'show_map', action: :show_map, on: :collection
  end

  resources :fire_departments

  resources :address_types

  resources :transferences, except: [:edit, :update], path_names: { destroy: 'undone' } do
    get 'search', action: :search, on: :collection # params: see action on controller
    get "set_place", action: :set_place, on: :collection# params: place_id
    get "add_vehicles", action: :add_vehicle, on: :collection# params: ids_on_list, vehicle_id
    get "add_firemen", action: :add_fireman, on: :collection# params: ids_on_list, fireman_id
    get "remove_vehicle", action: :remove_vehicle, on: :collection# params: ids_on_list, vehicle_id
    get "remove_fireman", action: :remove_fireman, on: :collection# params: ids_on_list, fireman_id
  end

  resources :people

  devise_for :users, path: 'auth', skip: [:registrations], path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }, controllers: {
    sessions: 'sessions'
  }

  get "guards/history", :to => 'guards#search', as: :guards_search
  get "guards/active"
  get "guards/add_guard_group"
  get "guards/add_editing"
  post "guards/update"
  delete "guards/destroy/:fireman_id", to: 'guards#destroy', as: :guards_destroy

  resources :dispatches, except: [:edit, :update, :index, :show, :destroy, :new] do
    get 'add_vehicle/:vehicle_id', action: 'add_vehicle', on: :collection, format: :json, as: 'add_vehicle'
    get 'add_fireman/:vehicle_id/:fireman_id', action: 'add_fireman', on: :collection, format: :json, as: 'add_fireman'
    new { get ':complaint_id', action: 'new', as: '' }
    get 'report', action: :report, as: 'report', on: :member
  end

    resources :users
    resources :users, path: "admins", as: "admins"

end

app/models/guard_group.rb
class GuardGroup < ActiveRecord::Base
  acts_as_any
  has_many :firemen_guard_groups, class_name: ::FiremenGuardGroups
  has_many :firemen, through: :firemen_guard_groups

  validates :name, presence: true, format: { with: ValidationRegexp.for(:name),
    message: ValidationRegexp.message_for(:name) }, length: { in: 3..40 }

  accepts_nested_attributes_for :firemen_guard_groups, allow_destroy: true, reject_if: :all_blank
end

app/controllers/guard_groups_controller.rb
class GuardGroupsController < ApplicationController

  include UsersControllable
  before_action :set_guard_group, only: [:show, :edit, :update, :destroy]
  before_action :set_variables, only: [:create, :edit, :new, :update]

  # GET /guard_groups
  # GET /guard_groups.json
  def index
    @query = GuardGroup.search(query_param)
    @guard_groups = @query.result.page(page_param)
  end

  # GET /guard_groups/1
  # GET /guard_groups/1.json
  def show
  end

  # GET /guard_groups/new
  def new
    @guard_group = GuardGroup.new
  end

  # GET /guard_groups/1/edit
  def edit
  end

  # POST /guard_groups
  # POST /guard_groups.json
  def create
    puts params.inspect
    @guard_group = GuardGroup.new(guard_group_params)
    @guard_group.firemen_guard_groups.destroy_all
    @guard_group.firemen = Fireman.where(["id in (?)", firemen_ids_params])
    respond_to do |format|
      if @guard_group.save
        format.html { redirect_to @guard_group, notice: 'Guard group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @guard_group }
      else
        format.html { render action: 'new' }
        format.json { render json: @guard_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guard_groups/1
  # PATCH/PUT /guard_groups/1.json
  def update
    @guard_group.firemen_guard_groups.destroy_all
    @guard_group.firemen = Fireman.where(["id in (?)", firemen_ids_params])    
    respond_to do |format|
      if @guard_group.update(guard_group_params)
        format.html { redirect_to @guard_group, notice: 'Guard group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @guard_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guard_groups/1
  # DELETE /guard_groups/1.json
  def destroy
    @guard_group.destroy
    respond_to do |format|
      format.html { redirect_to guard_groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guard_group
      @guard_group = GuardGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guard_group_params
      params.require(:guard_group).permit(:name, :description)
    end

    def firemen_ids_params
      params.require(:fireman_ids).compact if params[:fireman_ids]
    end

    def query_param
      params.require(:q) if params[:q]
    end

end

app/helpers/guard_groups_helper.rb
module GuardGroupsHelper

  def select_table list, options
    options.stringify_keys!
    html_options = { class: "form-control combobox #{options['class']}", 
      id: options['id'], data: { :"select-table-wrapper" => options['wrapper'], 
      :"select-table-attributes" => options['attributes'], 
      :"select-table-name" => options['name'], :"select-table-hidden-attributes" => options["hidden_attributes"] }  }
    select_options = ''
    select_options = content_tag(:option, options["prompt"], value: '') if options["prompt"]
    list.each do |item|  
      display = []
      data = {}
      options['attributes'].each do |attr|
        value = item.send(attr)
        data["attribute-#{attr}"] = value
        display << value
      end
      options["hidden_attributes"].each do |attr|
        data["hidden-attribute-#{attr}"] = item.send(attr)
      end
      select_options << content_tag(:option, display.join(' - '),  value: item.id, 
        data: data )
    end
    select_tag(nil, raw(select_options).html_safe, html_options)
  end
end

app/views/guard_groups/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= form_for(@guard_group, html: { role: 'form' }, validate: true) do |guard_groups_form| %>
      <% if @guard_group.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@guard_group.errors.count, "error") %>
            prohibited this guard_group from being saved:</h2>
          <ul>
            <% @guard_group.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= guard_groups_form.label :name, t('general.attributes.name').capitalize   %><br>
        <%= guard_groups_form.text_field :name, class: 'form-control'  %>
      </div>
      <div class="form-group">
        <%= guard_groups_form.label :description, t('general.attributes.description').capitalize   %><br>
        <%= guard_groups_form.text_area :description, class: 'form-control'  %>
      </div>
      <fieldset id="fireman_data">
        <legend>
          <%= t('general.models.fireman').pluralize(I18n.locale).capitalize  %>
        </legend>

        <%= render partial: 'guards/change_fireman_select_by_user', locals: { fireman_select_id: 'user_fireman' } %>

        <%= select_table (@firemen - @guard_group.firemen), { selected: @selected_fireman_id, id: 'user_fireman', wrapper: '#firemen_list', attributes: ["code","full_name"], hidden_attributes: ['division_id'], name: 'fireman_ids[]', prompt: t('general.actions.search', entity: t('general.models.fireman')).capitalize } %>

        <%= render partial: 'firemen/summarized_list', locals: { firemen: @guard_group.firemen, tbody_id: 'firemen_list', show_actions: [] } %>
      </fieldset>

      <div class="row">
        <div class="col-lg-12 text-right actions">
          <%= actions[guard_groups_form] %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/guard_groups/edit.html.erb
<div class="col-lg-9">
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= t('general.editing', entity: t("general.models.guard_group")).capitalize %>
    </div>
    <div class="panel-body">
      <%= render partial: 'form', locals: { actions: actions(t('general.models.guard_group')) } %>
    </div>
  </div>
</div>

app/views/guard_groups/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-lg-5">
        <%= t('general.listing', entity: t('general.models.guard_group').pluralize(I18n.locale)).capitalize %>
      </div>
      <div class="col-lg-7">
        <%= panel_heading_search_form_for(@query, :name, :description) %>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <% if @guard_groups.empty? %>
      <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
        <%= t('general.registers_not_found') %>
      </div>
    <% else %>
      <div  class="table-responsive">
        <div class="dataTables_wrapper form-inline" role="grid">
          <table class="table table-hover dataTable no-footer">
            <thead>
              <tr>
                <th><%= t('general.attributes.name').capitalize %></th>
                <th><%= t('general.attributes.description').capitalize %></th>
                <th></th>
                <% if can? :edit, GuardGroup %><th></th><% end %>
                <% if can? :delete, GuardGroup %><th></th><% end %>
              </tr>
            </thead>
            <tbody>
              <% @guard_groups.each do |guard_group| %>
                <tr>
                  <td><%= truncate guard_group.name, length: 18 %></td>
                  <td><%= truncate guard_group.description, length: 18 %></td>
                  
                  <td class="action">
                    <%= link_to guard_group do %>
                      <span class="glyphicon glyphicon-info-sign"></span>
                      <%= t('general.links.show').capitalize %>
                    <% end %>
                  </td>
                  <% if can? :edit, GuardGroup %>
                      <td class="action">
                        <%= link_to edit_guard_group_path(guard_group) do %>
                          <span class="glyphicon glyphicon-pencil"></span>
                          <%= t('general.links.edit').capitalize %>
                        <% end %>
                      </td>
                    <% end %>
                    <% if can? :delete, GuardGroup %>
                        <td class="action">
                          <%= link_to guard_group, method: :delete, 
                    data: { confirm: t('general.are_you_sure') } do %>
                            <span class="glyphicon glyphicon-trash"></span>
                            <%= t('general.links.destroy').capitalize %>
                          <% end %>
                        </td>
                      <% end %>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        <% end %>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-lg-9">
            <%= will_paginate @guard_groups %>
          </div>
          <div class="col-lg-3 text-right">
            <% if can? :create, GuardGroup %><th>
              <%= link_to new_guard_group_path, class: 'btn btn-primary' do %>
                <span class="glyphicon glyphicon-plus"></span>
                <%= t('general.actions.create', entity: t('general.models.guard_group')).capitalize %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
</div>

app/views/guard_groups/new.html.erb
<div class="col-lg-9">
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= t('general.actions.create', entity: t('general.models.guard_group')).capitalize %>
    </div>
    <div class="panel-body">
      <%= render partial: 'form', locals: { actions: actions(t('general.models.guard_group')) } %>
    </div>
  </div>
</div>

app/views/guard_groups/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('general.models.guard_group').titleize %>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-lg-3"><b><%= t('general.attributes.name').capitalize %>:</b></div>
      <div class="col-lg-9"><%= @guard_group.name %></div>
    </div>
    <% unless (@guard_group.description || '').blank? %>
      <div class="row">
        <div class="col-lg-3"><b><%= t('general.attributes.description').capitalize %>:</b></div>
        <div class="col-lg-9"><%= @guard_group.description %></div>
      </div>
    <% end %>
    <% if @guard_group.firemen.length > 0 %>
      <h5><%= t('general.models.fireman').capitalize.pluralize(I18n.locale) %></h5>
      <%= render partial: 'firemen/summarized_list', locals: { firemen: @guard_group.firemen, show_actions: false, with_division: true } %>
    <% end %>
  </div>
  <div class="panel-footer">
    <%= link_to guard_groups_path, class: "btn btn-default"  do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      <%= t('general.links.back').capitalize %>
    <% end %>
    <% if can? :edit, GuardGroup %><th>
        <%= link_to edit_guard_group_path(@guard_group), class: 'btn btn-primary' do %>
          <span class="glyphicon glyphicon-pencil"></span>
          <%= t('general.links.edit').capitalize %>
        <% end %>
      <% end %>
    </div>
  </div>