config/routes.rb
FiredevsWebsystem::Application.routes.draw do

  resources :incident_types

  resources :final_notes, except: [:new], controller: :notes, type: FinalNote.to_s
  resources :in_progress_notes, except: [:new], controller: :notes, type: InProgressNote.to_s
  
  [:notes, :final_notes, :in_progress_notes].each do |note_kind|
    resources note_kind, except: [:new, :destroy] do 
      new{ get ':dispatch_id', action: 'new', as: '', controller: :notes, type: note_kind }
      get 'new_final/:dispatch_id', action: 'new_final', as: 'new_final', controller: :notes, type: note_kind, on: :collection
    end
  end
  resources :places

  root "complaints#new"

  resources :guard_groups

  resources :vehicles

  get "versions", :to => 'versions#index', as: :paper_trail_versions
  get 'version/:id', :to => 'versions#show', as: :paper_trail_version

  resources :fireman_hierarchies

  resources :firemen do
    get 'by_division/:division_id', action: :by_division, on: :collection
  end

  resources :fireman_classifications

  resources :divisions do
    get 'by_fire_department/:fire_department_id', action: :by_fire_department, on: :collection
  end

  resources :complaints, path_names: { destroy: 'mark_as_user_error' }  do 
    get 'report', action: :report, as: 'report', on: :member
    get 'mark_as_fake', action: :mark_as_fake, as: 'mark_as_fake', on: :member
    get 'search', action: :search, on: :collection # params: see action on controller
    get 'show_map', action: :show_map, on: :collection
  end

  resources :fire_departments

  resources :address_types

  resources :transferences, except: [:edit, :update], path_names: { destroy: 'undone' } do
    get 'search', action: :search, on: :collection # params: see action on controller
    get "set_place", action: :set_place, on: :collection# params: place_id
    get "add_vehicles", action: :add_vehicle, on: :collection# params: ids_on_list, vehicle_id
    get "add_firemen", action: :add_fireman, on: :collection# params: ids_on_list, fireman_id
    get "remove_vehicle", action: :remove_vehicle, on: :collection# params: ids_on_list, vehicle_id
    get "remove_fireman", action: :remove_fireman, on: :collection# params: ids_on_list, fireman_id
  end

  resources :people

  devise_for :users, path: 'auth', skip: [:registrations], path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }, controllers: {
    sessions: 'sessions'
  }

  get "guards/history", :to => 'guards#search', as: :guards_search
  get "guards/active"
  get "guards/add_guard_group"
  get "guards/add_editing"
  post "guards/update"
  delete "guards/destroy/:fireman_id", to: 'guards#destroy', as: :guards_destroy

  resources :dispatches, except: [:edit, :update, :index, :show, :destroy, :new] do
    get 'add_vehicle/:vehicle_id', action: 'add_vehicle', on: :collection, format: :json, as: 'add_vehicle'
    get 'add_fireman/:vehicle_id/:fireman_id', action: 'add_fireman', on: :collection, format: :json, as: 'add_fireman'
    new { get ':complaint_id', action: 'new', as: '' }
    get 'report', action: :report, as: 'report', on: :member
  end

    resources :users
    resources :users, path: "admins", as: "admins"

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  acts_as_coded
  acts_as_any
  acts_as_transferable

  belongs_to :division
  delegate :name, to: :division, allow_nil: true, prefix: true
   
  has_one :fire_department, through: :division
  delegate :name, to: :fire_department, allow_nil: true, prefix: true

  validates :code, format: { with: ValidationRegexp.for(:code),
    message: ValidationRegexp.message_for(:code) }, length: { in: 2..10 }

  def compound_name
    "#{code} - #{division_name}"
  end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  load_and_authorize_resource

  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]
  before_action :set_divisions, only: [:new, :edit, :create, :update]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @query = Vehicle.search(query_param)
    @vehicles = @query.result(distint: true).page(page_param)
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render action: 'show', status: :created, location: @vehicle }
      else
        format.html { render action: 'new' }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    def set_divisions
      @divisions = Division.includes(:fire_department).load
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:code, :division_id)
    end

    def query_param
      params.require(:q) if params[:q]
    end

    def page_param
      params.require(:page) if params[:page]
    end
end

app/views/vehicles/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= form_for(@vehicle, html: { role: 'form' }, validate: true) do |f| %>
      <% if @vehicle.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@vehicle.errors.count, "error") %>
            prohibited this vehicle from being saved:</h2>
          <ul>
            <% @vehicle.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <div class="row">
          <div class="col-lg-6">
            <%= f.label :code, t('attributes.vehicles.code').capitalize %><br>
            <%= f.text_field :code, class: 'form-control'  %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-lg-12">
            <%= f.label :division_id, t('attributes.vehicles.division_name').capitalize %><br>
            <%= f.collection_select(:division_id, @divisions, :id, :compound_name, {}, class: 'form-control') %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12 text-right actions">
          <%= actions[f] %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/vehicles/edit.html.erb
<div class="col-lg-9">
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= t('general.editing', entity: t("general.models.vehicle")).capitalize %>
    </div>
    <div class="panel-body">
      <%= render partial: 'form', locals: { actions: actions(t('general.models.fireman_hierarchy')) } %>
    </div>
  </div>
</div>

app/views/vehicles/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-lg-5">
        <%= t('general.listing', entity: t('general.models.vehicle').pluralize(I18n.locale)).capitalize %>
      </div>
      <div class="col-lg-7">
        <%= panel_heading_search_form_for(@query, :code, :fire_department_name, :division_place_name) %>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <% if @vehicles.empty? %>
      <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= t('general.registers_not_found') %>
      </div>
    <% else %>
      <div  class="table-responsive">
        <div class="dataTables_wrapper form-inline" role="grid">
          <table class="table table-hover dataTable no-footer">
            <thead>
              <tr>
                <th><%= t('attributes.vehicles.code').capitalize %></th>
                <th><%= t('models.fire_department').capitalize %></th>
                <th><%= t('models.division').capitalize %></th>
                <th><%= t('general.attributes.available').capitalize %></th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @vehicles.each do |vehicle| %>
                <tr>
                  <td><%= vehicle.code %></td>
                  <td><%= vehicle.fire_department_name %></td>
                  <td><%= vehicle.division_name %></td>
                  <td><%= t("general.#{(!!vehicle.available).to_s}_significant") %></td>
                  <td style="text-align:center">
                    <%= link_to edit_vehicle_path(vehicle), data: { no_turbolink: true }  do %>
                      <span class="glyphicon glyphicon-pencil"></span>
                      <%= t('general.links.edit').capitalize %>
                    <% end %>
                  </td>
                  <td style="text-align:center">
                    <%= link_to vehicle, method: :delete, data: { confirm: t('general.are_you_sure') } do %>
                      <span class="glyphicon glyphicon-trash"></span>
                      <%= t('general.links.destroy').capitalize %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>
  </div>
  <div class="panel-footer">
    <div class="row">
      <div class="col-lg-6">
        <%= will_paginate @vehicles %>
      </div>
      <div class="col-lg-6 text-right">
        <%= link_to new_vehicle_path, class: 'btn btn-primary' do %>
          <span class="glyphicon glyphicon-plus"></span>
          <%= t('general.actions.create', entity: t('general.models.vehicle')).capitalize %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/vehicles/new.html.erb
<div class="col-lg-9">
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= t('general.actions.create', entity: t('general.models.vehicle')).capitalize %>
    </div>
    <div class="panel-body">
      <%= render partial: 'form', locals: { actions: actions(t('general.models.vehicle')) } %>
    </div>
  </div>
</div>

app/views/vehicles/show.html.erb
<div class="col-lg-8">
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= t('general.models.vehicle').titleize %>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-lg-3"><b><%= t('attributes.vehicles.code').capitalize %>:</b></div>
        <div class="col-lg-9"><%= @vehicle.code %></div>
      </div>
      <div class="row">
        <div class="col-lg-3"><b><%= t('general.models.fire_department').capitalize %>:</b></div>
        <div class="col-lg-9"><%= @vehicle.fire_department_name %></div>
      </div>
      <div class="row">
        <div class="col-lg-3"><b><%= t('general.models.division').capitalize %>:</b></div>
        <div class="col-lg-9"><%= @vehicle.division_name %></div>
      </div>
    </div>
    <div class="panel-footer">
      <div class="row">
        <div class="col-lg-12 text-right">
          <%= link_to vehicles_path, class: "btn btn-default"  do %>
            <span class="glyphicon glyphicon-list-alt"></span>
            <%= t('general.links.back').capitalize %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>