config/routes.rb
FiredevsWebsystem::Application.routes.draw do

  resources :incident_types

  resources :final_notes, except: [:new], controller: :notes, type: FinalNote.to_s
  resources :in_progress_notes, except: [:new], controller: :notes, type: InProgressNote.to_s
  
  [:notes, :final_notes, :in_progress_notes].each do |note_kind|
    resources note_kind, except: [:new, :destroy] do 
      new{ get ':dispatch_id', action: 'new', as: '', controller: :notes, type: note_kind }
      get 'new_final/:dispatch_id', action: 'new_final', as: 'new_final', controller: :notes, type: note_kind, on: :collection
    end
  end
  resources :places

  root "complaints#new"

  resources :guard_groups

  resources :vehicles

  get "versions", :to => 'versions#index', as: :paper_trail_versions
  get 'version/:id', :to => 'versions#show', as: :paper_trail_version

  resources :fireman_hierarchies

  resources :firemen do
    get 'by_division/:division_id', action: :by_division, on: :collection
  end

  resources :fireman_classifications

  resources :divisions do
    get 'by_fire_department/:fire_department_id', action: :by_fire_department, on: :collection
  end

  resources :complaints, path_names: { destroy: 'mark_as_user_error' }  do 
    get 'report', action: :report, as: 'report', on: :member
    get 'mark_as_fake', action: :mark_as_fake, as: 'mark_as_fake', on: :member
    get 'search', action: :search, on: :collection # params: see action on controller
    get 'show_map', action: :show_map, on: :collection
  end

  resources :fire_departments

  resources :address_types

  resources :transferences, except: [:edit, :update], path_names: { destroy: 'undone' } do
    get 'search', action: :search, on: :collection # params: see action on controller
    get "set_place", action: :set_place, on: :collection# params: place_id
    get "add_vehicles", action: :add_vehicle, on: :collection# params: ids_on_list, vehicle_id
    get "add_firemen", action: :add_fireman, on: :collection# params: ids_on_list, fireman_id
    get "remove_vehicle", action: :remove_vehicle, on: :collection# params: ids_on_list, vehicle_id
    get "remove_fireman", action: :remove_fireman, on: :collection# params: ids_on_list, fireman_id
  end

  resources :people

  devise_for :users, path: 'auth', skip: [:registrations], path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }, controllers: {
    sessions: 'sessions'
  }

  get "guards/history", :to => 'guards#search', as: :guards_search
  get "guards/active"
  get "guards/add_guard_group"
  get "guards/add_editing"
  post "guards/update"
  delete "guards/destroy/:fireman_id", to: 'guards#destroy', as: :guards_destroy

  resources :dispatches, except: [:edit, :update, :index, :show, :destroy, :new] do
    get 'add_vehicle/:vehicle_id', action: 'add_vehicle', on: :collection, format: :json, as: 'add_vehicle'
    get 'add_fireman/:vehicle_id/:fireman_id', action: 'add_fireman', on: :collection, format: :json, as: 'add_fireman'
    new { get ':complaint_id', action: 'new', as: '' }
    get 'report', action: :report, as: 'report', on: :member
  end

    resources :users
    resources :users, path: "admins", as: "admins"

end

app/controllers/firemen_controller.rb
class FiremenController < ApplicationController
  load_and_authorize_resource
  before_action :set_fireman, only: [:show, :edit, :update, :destroy]
  before_action :set_form_variables, only: [:create, :edit, :new, :update]


  rescue_from DependentStillExists do |e|
    redirect_to users_path, alert: t('errors.messages.firemen.delete_same_user')
  end

  # GET by_division/:division_id.json
  def by_division
    @firemen = []
    begin 
      @firemen = Fireman.where(division_id: params.require(:division_id)).includes(:person)
    rescue ActiveRecord::RecordNotFound
    end
    respond_to do |format|
      format.json  { render :json =>  @firemen.as_json(include: :person) }
    end
  end

  # GET /firemen
  # GET /firemen.json
  def index
    @query = Fireman.search(query_param)
    @firemen =  @query.result.page(page_param)
  end

  # GET /firemen/1
  # GET /firemen/1.json
  def show
  end

  # GET /firemen/new
  def new
  end

  # GET /firemen/1/edit
  def edit
  end

  # POST /firemen
  # POST /firemen.json
  def create
    @fireman = Fireman.new(fireman_params)

    respond_to do |format|
      if @fireman.save
        format.html { redirect_to @fireman, notice: 'Fireman was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fireman }
      else
        format.html { render action: 'new' }
        format.json { render json: @fireman.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /firemen/1
  # PATCH/PUT /firemen/1.json
  def update
    respond_to do |format|
      if @fireman.update(fireman_params)
        format.html { redirect_to @fireman, notice: 'Fireman was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fireman.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firemen/1
  # DELETE /firemen/1.json
  def destroy
    @fireman.destroy
    respond_to do |format|
      format.html { redirect_to firemen_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fireman
      @fireman = Fireman.find(params[:id])
    end

    def set_form_variables
      @fireman ||= Fireman.new
      @person = @fireman.person || @fireman.build_person
      @division_list = Division.all
      @fireman_hierarchy_list = FiremanHierarchy.all
      @fireman_classification_list = FiremanClassification.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fireman_params
      params.require(:fireman).permit(:division_id, :fireman_hierarchy_id, 
        :fireman_classification_id, :person_id, :code,
        person_attributes: [ :id, :name, :last_name, :birth_date, :phone_number, :gender, :document,
          {addresses_attributes: [:id, :references, :name, :longitude, :latitude, :address_type_id, :_destroy]}, 
          :_destroy])
    end

    def query_param
      params.require(:q) if params[:q]
    end

end

app/views/firemen/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= nested_form_for(@fireman, html: { role: 'form' }, validate: true) do |f| %>
      <% if @fireman.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@fireman.errors.count, "error") %>
            prohibited this fireman from being saved:</h2>
          <ul>
            <% @fireman.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= render partial: 'people/form', locals: {foreign_form: f, actions: actions(t('general.models.fireman'))} %>
      <div class="form-group">
        <%= f.label :code, t('general.attributes.code').capitalize   %><br>
        <%= f.text_field :code, class: 'form-control'  %>
      </div>
      <div class="form-group">
        <%= f.label :division_id, t('general.models.division').capitalize %><br>
        <%= f.collection_select(:division_id, @division_list, :id, :compound_name, {}, class: 'form-control') %>
      </div>
      <div class="form-group">
        <%= f.label :fireman_hierarchy_id, t('general.models.fireman_hierarchy').capitalize   %><br>
        <%= f.collection_select(:fireman_hierarchy_id, @fireman_hierarchy_list, :id, :name, {}, class: 'form-control') %>
      </div>
      <div class="form-group">
        <%= f.label :fireman_classification_id, t('general.models.fireman_classification').capitalize   %><br>
        <%= f.collection_select(:fireman_classification_id, @fireman_classification_list, :id, :name, {}, class: 'form-control') %>
      </div>
      <div class="row">
        <div class="col-lg-12 text-right actions">
          <%= actions[f] %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/firemen/_summarized_list.html.erb
<% show_actions = [] if local_assigns[:show_actions].nil? %>
<% with_division = false if local_assigns[:with_division].nil? %>
<% removable_attribute = "data-select-table-removable-id" if local_assigns[:removable_attribute].nil? %>
<% tbody_id = "fireman_tbody_id" if local_assigns[:tbody_id].nil? %>
<% data_selectable_value = nil if local_assigns[:data_selectable_value].nil? %>
<% input_start_tag = "input" if local_assigns[:input_start_tag].nil? %>
<div  class="table-responsive">
  <div class="dataTables_wrapper form-inline" role="grid">
    <table class="table table-hover dataTable no-footer">
      <thead>
        <tr>
          <th><%= t('general.attributes.code').capitalize %></th>
          <th><%= t('general.attributes.full_name').capitalize %></th>
          <% if with_division %>
            <th class="text-center"><%= t('general.models.division').capitalize %></th>
          <% end %>
          <% if show_actions %>
            <th class="action"><%= t('general.links.delete').capitalize %></th>

            <% if show_actions.include?('guard') %>
              <th class="action">Guardia</th>
            <% end %>
          <% end %>
        </tr>
      </thead>
      <tbody id="<%= tbody_id %>" data-selectable-value="<%= data_selectable_value %>">
        <% firemen.each do |fireman| %>
          <tr <%= removable_attribute %>='<%= fireman.id %>'>
            <td><%= truncate fireman.code, length: 10 %></td>
            <td><%= truncate fireman.full_name, length: 30 %></td>

            <% if with_division %>
              <td class="text-center"><%= truncate fireman.division_code, length: 30 %></td>
            <% end %>

            <% if show_actions %>
              <td class="action">
                <%#= hidden_field_tag 'fireman_ids[]', fireman.id %>
                <<%= input_start_tag %> style="display:none; height: 0; width:0;" type="hidden" name='fireman_ids[]' value="<%= fireman.id %>" />
                <a href="#"  data-no-turbolink='true' data-fireman='<%= {text: "#{fireman.code} - #{fireman.full_name}", code: fireman.code, id: fireman.id, name: fireman.full_name, division_id: fireman.division_id}.to_json %>' <%= removable_attribute %>="<%= fireman.id %>" ><span class="glyphicon glyphicon-trash"></span></a>
              </td>
              <% if show_actions.include?('guard') %>
                <td class="action" style='width: 150px'>
                  <%= select_tag "guards[#{fireman.id}]", options_for_select(Guard.actions.options), {class: 'form-control', id: 'guard_status_select'} %>
                </td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/firemen/edit.html.erb
<div class="col-lg-9">
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= t('general.editing', entity: t("general.models.fireman")).capitalize %>
    </div>
    <div class="panel-body">
      <%= render partial: 'form', locals: { actions: actions(t('general.models.fireman')) } %>
    </div>
  </div>
</div>

app/views/firemen/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-lg-5">
        <%= t('general.listing', entity: t('general.models.fireman').pluralize(I18n.locale)).capitalize %>
      </div>
      <div class="col-lg-7">
        <%= panel_heading_search_form_for(@query, :code, :person_name, :person_last_name, :division_place_name, :fireman_hierarchy_name, :fireman_classification_name ) %>
      </div>
    </div>    
  </div>
  <div class="panel-body">
    <% if @firemen.empty? %>
      <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= t('general.registers_not_found') %>
      </div>
    <% else %>
      <div class="table-responsive">
        <div class="dataTables_wrapper form-inline" role="grid">
          <table class="table table-hover dataTable no-footer">
            <thead>
              <tr>
                <th><%= t('general.attributes.code').capitalize %></th>
                <th><%= t('general.attributes.name').capitalize %></th>
                <th><%= t('general.attributes.last_name').capitalize %></th>
                <th><%= t('general.models.division').capitalize %></th>
                <th><%= t('general.attributes.fireman.hierarchy').capitalize %></th>
                <th><%= t('general.attributes.fireman.classification').capitalize %></th>
                <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @firemen.each do |fireman| %>
                <tr>
                  <td><%= truncate fireman.code, length: 18 %></td>
                  <td><%= truncate fireman.name, length: 18 %></td>
                  <td><%= truncate fireman.last_name, length: 18 %></td>
                  <td class="text-center"><%= truncate fireman.division.code, length: 18 %></td>
                  <td><%= truncate fireman.fireman_hierarchy.name, length: 18 %></td>
                  <td><%= truncate fireman.fireman_classification.name, length: 18 %></td>

                  <td style="text-align:center">
                    <%= link_to fireman do %>
                      <span class="glyphicon glyphicon-info-sign"></span>
                      <%= t('general.links.show').capitalize %>
                    <% end %>
                  </td>
                  <td style="text-align:center">
                    <% if can? :edit, fireman %>
                      <%= link_to edit_fireman_path(fireman), data: { no_turbolink: true }  do %>
                        <span class="glyphicon glyphicon-pencil"></span>
                        <%= t('general.links.edit').capitalize %>
                      <% end %>
                    <% end %>
                  </td>
                  <td style="text-align:center">
                    <% if can? :delete, fireman %>
                      <%= link_to fireman, method: :delete, 
                      data: { confirm: t('general.are_you_sure') } do %>
                        <span class="glyphicon glyphicon-trash"></span>
                        <%= t('general.links.destroy').capitalize %>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>
  </div>
  <div class="panel-footer">
    <div class="row">
      <div class="col-lg-9">
        <%= will_paginate @firemen %>
      </div>
      <div class="col-lg-3 text-right">
        <% if can? :create, Fireman %><th>
          <%= link_to new_fireman_path, class: 'btn btn-primary', data: { no_turbolink: true }  do %>
            <span class="glyphicon glyphicon-plus"></span>
            <%= t('general.actions.create', entity: t('general.models.fireman')).capitalize %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/firemen/new.html.erb
<div class="col-lg-9">
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= t('general.actions.create', entity: t('general.models.fireman')).capitalize %>
    </div>
    <div class="panel-body">
      <%= render partial: 'form', locals: { actions: actions(t('general.models.fireman')) } %>
    </div>
  </div>
</div>

app/views/firemen/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('general.models.fireman').titleize %>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-lg-3"><b><%= t('general.models.division').capitalize %>:</b></div>
      <div class="col-lg-9"><%= @fireman.division.name %></div>
    </div>
    <div class="row">
      <div class="col-lg-3"><b><%= t('general.attributes.fireman.hierarchy').capitalize %>:</b></div>
      <div class="col-lg-9"><%= @fireman.fireman_hierarchy.name %></div>
    </div>
    <div class="row">
      <div class="col-lg-3"><b><%= t('general.attributes.fireman.classification').capitalize %>:</b></div>
      <div class="col-lg-9"><%= @fireman.fireman_classification.name %></div>
    </div>
    <div class="row">
      <div class="col-lg-3"><b><%= t('general.attributes.name').capitalize %>:</b></div>
      <div class="col-lg-9"><%= @fireman.name %></div>
    </div>
    <div class="row">
      <div class="col-lg-3"><b><%= t('general.attributes.last_name').capitalize %>:</b></div>
      <div class="col-lg-9"><%= @fireman.last_name %></div>
    </div>
    <div class="row">
      <div class="col-lg-3"><b><%= t('general.attributes.birth_date').capitalize %>:</b></div>
      <div class="col-lg-9"><%= @fireman.birth_date %></div>
    </div>
    <div class="row">
      <div class="col-lg-3"><b><%= t('general.attributes.phone_number').capitalize %>:</b></div>
      <div class="col-lg-9"><%= @fireman.phone_number %></div>
    </div>
    <% @fireman.person.addresses.each do |address| %>
      <div class="row">
        <div class="col-lg-3"><b><%= t('general.attributes.address').capitalize %>
            (<%= address.address_type.name %>):</b></div>
        <div class="col-lg-9"><%= address.name %></div>

        <% unless address.references.nil? or address.references.empty? %>
          <div class="col-lg-3"><b><%= t('general.attributes.references').capitalize %>:</b></div>
          <div class="col-lg-9"> <%= address.references %> </div>
        <% end %>
      </div>

      <div class="row">
        <div class="col-lg-12">
          <%= gmap_show(address.latitude, address.longitude, address.hash.abs) %>
        </div>
      </div>
    <% end %>
    <div class="row">
      <div class="col-lg-3"><b><%= t('general.attributes.gender').capitalize %>:</b></div>
      <div class="col-lg-9"><%= @fireman.gender %></div>
    </div>
  </div>
  <div class="panel-footer">
    <%= link_to firemen_path, class: "btn btn-default"  do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      <%= t('general.links.back').capitalize %>
    <% end %>
    <% if can? :edit, @fireman %>
      <%= link_to edit_fireman_path(@fireman), class: 'btn btn-primary', data: { no_turbolink: true }  do %>
        <span class="glyphicon glyphicon-pencil"></span>
        <%= t('general.links.edit').capitalize %>
      <% end %>
    <% end %>
  </div>
</div>